apiVersion: v1
kind: Pod
metadata:
  name: k8s-db
  labels:
    name: lbl-k8s-db
spec:
  containers:
  - name: oracledb
    image: bom.ocir.io/sehubjapacprod/oracledb/oracledb19c/oracle.19.3.0-ee:oracle19.3.0-ee
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mydb-pass
          key: password
    ports:
    - name: db
      containerPort: 3306
      protocol: TCP
    volumeMounts:
    - name: k8s-db-storage
      mountPath: /var/lib/db
  volumes:
  - name: k8s-db-storage
    emptyDir: {}
  imagePullSecrets:
    - name: ocirsecret
